### RoomCategory
### 전체 방 카테고리 목록 불러오기
GET http://localhost:3000/api/rooms/categories

### Room
### 전체 방 목록 불러오기
GET http://localhost:3000/api/rooms

### "휴식" 카테고리의 방 목록 불러오기
GET http://localhost:3000/api/rooms?categoryName=학습

### 방 자세히 불러오기
GET http://localhost:3000/api/rooms/3

### 방 등록하기
POST http://localhost:3000/api/rooms
Content-Type: application/json
Authorization: Bearer {{$dotenv authToken }}

{
  "title": "테스트2",
  "categoryId": 3,
  "light": "TWO",
  "wallColor": "GREEN",
  "objectIds": {
    "board": 1,
    "clock": 1,
    "light": 1,
    "poster": 1,
    "speaker": 1,
    "table": 1,
    "vase": 1,
    "wall": 1
  },
  "background": "SUNNY",
  "assets": [{
    "type": "image",
    "url": "https://floom-upload.s3.ap-northeast-2.amazonaws.com/5X6Dt7ri3__2a0hiak8KJ.png"
  }],
  "tags": ["test1", "test2"],
  "roomImage": "https://floom-upload.s3.ap-northeast-2.amazonaws.com/-ruDAbdraL_7P6z7ZXRHs.png",
  "musicIds": [4, 5, 6]
}

### MusicCategory
### 전체 음악 카테고리 목록 불러오기
GET http://localhost:3000/api/musics/categories

### Music
### 음악 목록 불러오기
GET http://localhost:3000/api/musics

### 카테고리 별로 음악 목록 불러오기
GET http://localhost:3000/api/musics?categoryId=1

### Review
### 리뷰 등록
POST http://localhost:3000/api/reviews
Content-Type: application/json

{
  "roomId": 1,
  "objective": "123",
  "comment": "123",
  "recommend": false
}

### Common
### pre-signed 업로드 생성하기
POST http://localhost:3000/api/common/pre-upload
Content-Type: application/json
Authorization: Bearer {{$dotenv authToken }}

{
  "filename": "a.png",
  "contentType": "image/png"
}
